version: "3"

services:
  db:
    image: postgres:9.6
    restart: always

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - 5432:5432

    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .

    restart: always
    ports:
      - 8083:3000

    entrypoint: ./init.sh

    env_file:
      - .env

    depends_on:
      - db
