package domain

// Status ...
type Status string

const (
	// Paid ...
	Paid Status = "paid"
	// NotPaid ...
	NotPaid Status = "not_paid"
)

// PaymentMethod ...
type PaymentMethod string

const (
	// Money ...
	Money PaymentMethod = "money"
	// Transfer ...
	Transfer PaymentMethod = "transfer"
	// Scheduled ...
	Scheduled PaymentMethod = "scheduled"
)
